Donation page #16
CatimaLoyalty/Website pull request #28
Opened 2023-09-08 17:27 UTC by Tjs002

Donation Page added

2023-09-09 15:20 UTC, TheLastProject requested changes
I strongly suggest you follow a markdown tutorial. HTML tags should only be used for features Markdown doesn't support, but you used them everywhere, even for features that Markdown does support.

Also, you added a lot of extra style attributes, causing this page to look completely different from all the other pages and ignore the global website theming. If this page's design would be unique, that would be understandable, but it isn't unique in any way, so now it just has a different font size and style than the rest of the website for... no real reason?

The general structure is fine though, so let's start with removing all of the HTML tags where possible (really, almost everything here can be Markdown, even the donate buttons!). And then we can look at the text so it's not a one-on-one copy of the KISS website :)

2023-09-09 18:26 UTC, Tjs002 commented on _pages/donate.md
> +</p>
The text is just for review can change it after the review and let me know what text should be used.

2023-09-09 18:27 UTC, Tjs002 commented on _pages/donate.md
> +# Donate to CATIMA
ok i will change the tags to the markdown. let me know how to create buttons in markdown

2023-09-16 17:04 UTC, obfusk commented
I'm sorry, I didn't have time this week but I'm hoping to have time to review and help improve the wording etc. a bit next week. Thanks for the help!

2023-09-20 11:29 UTC, Tjs002 commented
> I'm sorry, I didn't have time this week but I'm hoping to have time to review and help improve the wording etc. a bit next week. Thanks for the help!

Yaa no worries...Let me know if i can assist for further help

2023-09-28 15:57 UTC, closed without merging